version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - ALLOW_ORIGINS=${ALLOW_ORIGINS}

    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - NEXT_PUBLIC_APP_NAME=FlowTrack
      - NEXT_PUBLIC_VERSION=1.0.0
      - NEXT_PUBLIC_DEBUG=false
      - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - APP_NAME="FlowTrack API"
      - VERSION=1.0.0
      - DEBUG=False
      - MODE='production'
    ports:
      - "3000:3000"
    depends_on:
      - server
