version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: flowtrack_db
    environment:
      POSTGRES_USER: flowtrack_user
      POSTGRES_PASSWORD: flowtrack_pass
      POSTGRES_DB: flowtrack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowtrack_user -d flowtrack_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (Valkey compatible)
  redis:
    image: redis:7-alpine
    container_name: flowtrack_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # FastAPI Backend (optional - for production)
  # api:
  #   build: .
  #   container_name: flowtrack_api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_URL: postgresql+asyncpg://flowtrack_user:flowtrack_pass@postgres:5432/flowtrack_db
  #     REDIS_URL: redis://redis:6379/0
  #     JWT_SECRET: your-secret-key-here
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   volumes:
  #     - ./app:/app/app
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  redis_data:
